# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_yaml12_wrappers", use_symbols = TRUE, package_name = "yaml12")

#' @usage NULL
#' @useDynLib yaml12, .registration = TRUE
NULL

#' Parse YAML 1.2 document(s) into base R structures.
#'
#' Supports scalars, sequences, and mappings; YAML tags are preserved in a
#' `yaml_tag` attribute when possible. YAML aliases are rejected.
#' @param text Character vector; elements are concatenated with `"\n"`.
#' @param multi When `TRUE`, return a list containing all documents in the stream.
#' @export
parse_yaml <- function(text, multi = FALSE) .Call(wrap__parse_yaml, text, multi)

#' Encode an R object as YAML 1.2.
#'
#' @param value Any R object composed of lists, atomic vectors, and scalars.
#' @param multi When `TRUE`, treat `value` as a list of YAML documents and encode a stream.
#' @return A scalar character string containing YAML.
#' @export
encode_yaml <- function(value, multi = FALSE) .Call(wrap__encode_yaml, value, multi)

#' Read YAML 1.2 document(s) from a file path.
#'
#' @param path Scalar string path to a YAML file.
#' @param multi When `TRUE`, return a list containing all documents in the stream.
#' @export
read_yaml <- function(path, multi = FALSE) .Call(wrap__read_yaml, path, multi)

#' Write an R object as YAML 1.2 to a file.
#'
#' @param value Any R object composed of lists, atomic vectors, and scalars.
#' @param path Scalar string file path to write YAML to.
#' @param multi When `TRUE`, treat `value` as a list of YAML documents and encode a stream.
#' @return Invisibly returns `NULL`.
#' @export
write_yaml <- function(value, path, multi = FALSE) .Call(wrap__write_yaml, value, path, multi)


# nolint end
