# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_yaml12_wrappers", use_symbols = TRUE, package_name = "yaml12")

#' @usage NULL
#' @useDynLib yaml12, .registration = TRUE
NULL

#' Parse YAML 1.2 document(s) into base R structures.
#'
#' Supports scalars, sequences, and mappings; YAML tags are preserved in a
#' `yaml_tag` attribute when possible. YAML anchors and aliases are resolved
#' by the parser, so aliases behave like copies of their target nodes.
#' @param text Character vector; elements are concatenated with `"\n"`.
#' @param multi When `TRUE`, return a list containing all documents in the stream.
#' @param simplify When `FALSE`, keep YAML sequences as R lists instead of simplifying to atomic vectors.
#' @param handlers Named list of R functions keyed by YAML tag strings; matching handlers transform tagged values.
#' @export
parse_yaml <- function(text, multi = FALSE, simplify = TRUE, handlers = NULL) .Call(wrap__parse_yaml, text, multi, simplify, handlers)

#' Format an R object as YAML 1.2.
#'
#' When `multi = TRUE`, emits document start markers (`---`) and ends the
#' stream with a trailing newline. When `multi = FALSE`, writes a single
#' document node without a start marker and no final newline. Honors a
#' `yaml_tag` attribute on values (see examples).
#'
#' @param value Any R object composed of lists, atomic vectors, and scalars.
#' @param multi When `TRUE`, treat `value` as a list of YAML documents and encode a stream.
#' @return A scalar character string containing YAML.
#' @export
#' @examples
#' cat(format_yaml(list(foo = 1, bar = list(TRUE, NA))))
#' 
#' docs <- list("first", "second")
#' cat(format_yaml(docs, multi = TRUE))
#'
#' tagged <- structure("1 + x", yaml_tag = "!expr")
#' cat(tagged_yaml <- format_yaml(tagged), "\n")
#' attr(parse_yaml(tagged_yaml), "yaml_tag")
format_yaml <- function(value, multi = FALSE) .Call(wrap__format_yaml, value, multi)

#' Read YAML 1.2 document(s) from a file path.
#'
#' @param path Scalar string path to a YAML file.
#' @param multi When `TRUE`, return a list containing all documents in the stream.
#' @param simplify When `FALSE`, keep YAML sequences as R lists instead of simplifying to atomic vectors.
#' @param handlers Named list of R functions keyed by YAML tag strings; matching handlers transform tagged values.
#' @export
read_yaml <- function(path, multi = FALSE, simplify = TRUE, handlers = NULL) .Call(wrap__read_yaml, path, multi, simplify, handlers)

#' Write an R object as YAML 1.2 to a file.
#'
#' Writes the YAML stream to a file or stdout and always emits explicit document
#' start (`---`) markers and a final end (`...`) marker. Respects `yaml_tag`
#' attributes when encoding values.
#'
#' @param value Any R object composed of lists, atomic vectors, and scalars.
#' @param path Scalar string file path to write YAML to. When `NULL` (the default),
#'   write to R's standard output connection.
#' @param multi When `TRUE`, treat `value` as a list of YAML documents and encode a stream.
#' @return Invisibly returns `value`.
#' @export
#' @examples
#' write_yaml(list(foo = 1, bar = list(2, "baz")))
#'
#' write_yaml(list("foo", "bar"), multi = TRUE)
#'
#' tagged <- structure("1 + x", yaml_tag = "!expr")
#' write_yaml(tagged)
write_yaml <- function(value, path = NULL, multi = FALSE) invisible(.Call(wrap__write_yaml, value, path, multi))


# nolint end
